(in-package #:telnet-stream)

(defconstant +WILL+ 251)
(defconstant +WONT+ 252)
(defconstant +DO+ 253)
(defconstant +DONT+ 254)
(defconstant +IAC+ 255)

(defvar *known-commands*
  `((,+WILL+ . :WILL)
    (,+WONT+ . :WONT)
    (,+DO+ . :DO)
    (,+DONT+ . :DONT)))

;; http://www.thoughtproject.com/Libraries/Telnet/Reference/Options.htm
(defvar *known-options*
  '((00 . :TRANSMIT-BINARY)
    (01 . :ECHO)
    (03 . :SUPPRESS-GO-AHEAD)
    (05 . :STATUS)
    (06 . :TIMING-MARK)
    (10 . :NAOCRD)
    (11 . :NAOHTS)
    (12 . :NAOHTD)
    (13 . :NAOFFD)
    (14 . :NAOVTS)
    (15 . :NAOVTD)
    (16 . :NAOLFD)
    (17 . :EXTEND-ASCII)
    (18 . :LOGOUT)
    (19 . :BM)
    (20 . :DET)
    (23 . :SEND-LOCATION)
    (24 . :TERMINAL-TYPE)
    (25 . :END-OF-RECORD)
    (26 . :TUID)
    (27 . :OUTMRK)
    (28 . :TTYLOC)
    (29 . :3270-REGIME)
    (30 . :X.3-PAD)
    (31 . :NAWS)
    (32 . :TERMINAL-SPEED)
    (33 . :TOGGLE-FLOW-CONTROL)
    (34 . :LINEMODE)
    (35 . :X-DISPLAY-LOCATION)
    (36 . :ENVIRON)
    (37 . :AUTHENTICATION)
    (38 . :ENCRYPT)
    (39 . :NEW-ENVIRON)
    (40 . :TN3270E)
    (42 . :CHARSET)
    (44 . :COM-PORT-OPTION)
    (47 . :KERMIT)))
